### ISSUE TITLE
Bruno CA Certificates

### ISSUE THREAD

**Issue by helloanoop** [usebruno/bruno#1326]
Creating this issue to keep a track of all things related to CA certificates.

- [ ] Allow specifying additional CA certificates #1080, #211, #739
- [ ] Allow collection level CA certificate #1324
- [ ] Allow SSL validation to be turned off at request level #1325
