### ISSUE TITLE
Auth: Cookies

### ISSUE THREAD

**Issue by Tanja-4732** [usebruno/bruno#968]
This project _really_ needs to support storing and automatically re-sending cookies, just like a browser would.

I'll work on an PR for this:

I'll work on cookies [in my fork](https://github.com/Tanja-4732/bruno) since you seem to be working on auto-save.

I hope to have some progress by the end of the week; will (hopefully) open a draft-PR until then

_Originally posted by @Tanja-4732 in https://github.com/usebruno/bruno/discussions/385#discussioncomment-7571305_

### Tasks
- [x]  Basic Cookie Support
- [ ] CLI Support
- [x] Delete a cookie in UI
- [ ] Edit a cookie in UI
- [ ] Add a cookie in UI
- [ ] Add a new domain/url in UI

**Comment by nu111** [comment]
I am trying to move away from Insomnia or Postman, I would like to try Bruno, but I can't without cookies. I'd love to see this feature!

**Comment by solsticesurfer** [comment]
+1 on cookie support. It's the only thing preventing my team from dumping Postman and moving over to Bruno. Far too many systems rely on a session cookie as part of their authentication flow.

**Comment by chriswinter90** [comment]
+1 for many at our company. We use sessions on some of our node apps and the session id changes every time because the cookie is not saved causing a new session each time so no user info is persisted.

**Comment by Tanja-4732** [comment]
Yes yes, I'll try to get started on this till about Monday,  
though I'm not very familiar with the codebase yet

**Comment by joe-gre** [comment]
I'm trying to get cookie based auth working, but I don't think its sending the cookie header. Here is what I have in the Headers tab, which works in Postman but not Bruno: 

![image](https://github.com/usebruno/bruno/assets/22748761/21615b52-aecf-4805-9d3d-ca1d925c3d9f)

I tried setting the session cookie to valid string literal session ids too, both encoded and not encoded. Same issue.

Also FYI this is what I have in the post script to decode the cookie response and set it as a context var. This part is working well.
```
const header = res.getHeader("set-cookie")?.[0];
if (!header) return;

const session = header.substring(
  header.indexOf("=") + 1,
  header.indexOf(";")
);
bru.setVar("session", decodeURIComponent(session));
console.log(`session: ${bru.getVar("session")}`)
```

**Comment by joe-gre** [comment]
I see that it is sending the cookie header actually. But its not sending it as a signed cookie like it is in Postman. Unfortunately this is a blocker for our team's adoption of Bruno. I've been waiting for an API client that saves collections to file systems. I hope this feature gets added so we can migrate.

**Comment by joe-gre** [comment]
> I'm trying to get cookie based auth working, but I don't think its sending the cookie header. Here is what I have in the Headers tab, which works in Postman but not Bruno:
> 
> ![image](https://user-images.githubusercontent.com/22748761/283943471-21615b52-aecf-4805-9d3d-ca1d925c3d9f.png)
> 
> I tried setting the session cookie to valid string literal session ids too, both encoded and not encoded. Same issue.
> 
> Also FYI this is what I have in the post script to decode the cookie response and set it as a context var. This part is working well.
> 
> ```
> const header = res.getHeader("set-cookie")?.[0];
> if (!header) return;
> 
> const session = header.substring(
>   header.indexOf("=") + 1,
>   header.indexOf(";")
> );
> bru.setVar("session", decodeURIComponent(session));
> console.log(`session: ${bru.getVar("session")}`)
> ```

I got this working by changing the auth type to "No Auth". Now authentication works!

**Comment by Tanja-4732** [comment]
So far, I've added a button for a cookie tab, which is yet to be implemented:

![image](https://github.com/usebruno/bruno/assets/18219148/9e8b29fe-3239-4e18-859f-35ae16cf7778)
![image](https://github.com/usebruno/bruno/assets/18219148/bd79a45b-9c4b-4854-a46f-f7d742f8c6aa)

**Comment by Tanja-4732** [comment]
> I've been waiting for an API client that saves collections to file systems

Same, but we seemingly all need cookie support for this to be of basically any use.

I think I may have _some_ form of this available within the next week, provided I find the time.

See #969 for details

**Comment by Tanja-4732** [comment]
> I've been waiting for an API client that saves collections to file systems

Same, but we seemingly all need cookie support for this to be of basically any use.

I think I may have _some_ form of this available within the next week, provided I find the time.

See #969 for details

**Comment by Tanja-4732** [comment]
More good news:

![image](https://github.com/usebruno/bruno/assets/18219148/68e1d342-ea20-4b77-a7a3-0b6b986ed5a9)

We now have a basic cookie tab;  
But the under-the-hood features/implementation is not yet here

**Comment by Tanja-4732** [comment]
More good news:

![image](https://github.com/usebruno/bruno/assets/18219148/eb09ec7f-b55b-4b09-926d-c12f253abd50)

We now have a basic cookie tab;
But the under-the-hood features/implementation is not yet here

**Comment by Tanja-4732** [comment]
### Basic cookie store works now

However, I've yet to implement sending them along automatically.

---

Notice, how the login now correctly sets the `session_token` collection-wide in the example below:
(but #969 still needs to be merged first)



![image](https://github.com/usebruno/bruno/assets/18219148/6017e1ed-a55b-477b-966d-e67e63430489)

**Comment by Tanja-4732** [comment]
Update:

# It's working now

My fork on branch `feature/cookies` now has out-of-the-box cookie support :tada:

**Comment by Tanja-4732** [comment]
Someone please review #969

**Comment by joe-gre** [comment]
Thanks cookie authentication is working well!

**Comment by Tanja-4732** [comment]
Well, while my fork https://github.com/Tanja-4732/bruno/tree/feature/cookies worked very well for my usecases,  
there are isssues:

Mostly related to the fact that I did cookies per-collection, whereas @helloanoop wanted them app-wide, and I forgot to consider host names, as I only developed against one API server.

See this discussed in https://github.com/usebruno/bruno/pull/969#issuecomment-1818784536

---

All in all, my PR #969 seems very dead rn, but at least my work may have showed that cookie support is important enough  to be implemented sooner than planned originally :woman_shrugging: 

So @joe-gre, your 
> Thanks cookie authentication is working well!

may actually reference e1a96e0 rather than my #969

---

Thanks again for all the :tada:s, :heart:s, and the :+1:s, I really appreciate them :blush:

**Comment by DrGrognon** [comment]
Hello , Thanks a lot for the work and this really promising Bruno :dog2: 

If found something annoying with cookie that i think may be of interest for implementer
A feature that would be helpfull with cookie support, would be ability to disbale cookie jar at a request or collection level.

**My really annoying use case**: When doing CSRF mitigation by the use of double submit cookie ( [good explanation here](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie)  ) , if cookie are auto set and cannot be disabled, this make CSRF handling mandatory.

If one can just disable the cookies, no more cookie no more CSRF, no more problem :smile: 

FYI functionnality look like that in postman:
![image](https://github.com/usebruno/bruno/assets/46163392/e30b9c73-cb23-4675-8ac7-415dd673188f)

**Comment by helloanoop** [comment]
@DrGrognon You can conditionally disable cookies in `v1.3.0`

![image](https://github.com/usebruno/bruno/assets/9350733/101ef7f6-859b-43dd-9f38-40488814ca7a)

**Comment by DrGrognon** [comment]
@helloanoop I just tried it, and it do the job perfectly :smiley:  !
I'm really pleased to see such good momentum and spirit around Bruno,
Thanks a lot an keep going :dog: :heart:

**Comment by r-polunin** [comment]
Thank you for all your cookie related extension, this one is really mandatory for my company.
Unfortunately current implementation does not cover my case:

If we have a chain of requests, i.e: request -> 302 re-direct -> 302 re-direct -> page.
Cookies from the first re-direct response are not propagated further.

In my case I have a POST request with auth params as a first step where correct cookies with authorized JSESSIONID are set, but they are lost after following re-direction with 302 code and overwritten by newly set JSESSIONID without auth from the target page.

curl handles such request properly with --cookie-jar, postman handles it OOB, would be great if Bruno could support such case too.

**Comment by lltr** [comment]
Was looking at the docs trying to copy a cookie from the browser over to Bruno to test but couldn't figure out a way to and realized that there isn't a way to do it. Hopefully this will be added soon enough so I no longer need to use Postman as it is essential to my current workflow.

**Comment by r-polunin** [comment]
I had a free weekend to dive a little deeper:
@lltr I've added a capability to set cookies manually in the fork: https://github.com/r-polunin/bruno/tree/cookies-for-redirects
You can try to use this one, while we wait for official version of the feature :D
(It doesn't show Secure, HttpOnly etc. property yet and I don't promise stable behaviour, but it worked for me, possibly it will cover your cases too)
<img width="788" alt="image" src="https://github.com/usebruno/bruno/assets/6052992/41f590d8-b5b9-44b3-9328-89f6667a1a88">

@helloanoop, regarding my previous comment:
> If we have a chain of requests, i.e: request -> 302 re-direct -> 302 re-direct -> page.
Cookies from the first re-direct response are not propagated further.
This happens because of the way how axios works:
https://github.com/axios/axios/issues/3862
I've raised a pull request to merge a workaround for this one:
https://github.com/usebruno/bruno/pull/1463
Could you please comment on the changes?

**Comment by zFlxw** [comment]
Hi. First of all, thanks for your contribution, cookies are pretty much the only feature I really need and that prevented me from switching to Bruno. I got a bit confused, so I may ask if anyone can tell me what the current status of the cookie implementation is? I assume it has not officially been merged, but how profound is the current implementation?

**Comment by kizilcali81** [comment]
Hi. Thank you all for this awesome feature. This was really important for us. @helloanoop Is there any chance that we see the cookie support also in Bruno CLI any time soon? It is a bit annoying that we can not run our tests in the CLI the same way as we do with the collection runner.

**Comment by Goufoux** [comment]
Hello, thanks for the feature, like kizilcali81, i asking if the feature should be avaiable in the cli too ?

**Comment by brad** [comment]
As a workaround I'm turning off the automatic cookie handling in preferences as mentioned [here](https://github.com/usebruno/bruno/issues/968#issuecomment-1836839623) and then I run `req.setHeader("Cookie", '{{cookie}}')` in the pre request script

**Comment by Infinitay** [comment]
Is it possible to do something similar to Insomnia where you can set the authorization header to `Cookie <cookie_key>` directly into the headers field without scripting? I've tried things like like `Cookie {{<cookie_key>}}` `Cookie {{headers.cookie.key}}` `Cookie {{cookie.key}}` `Cookie {{req.cookie.key}}` `Cookie {{request.cookie.key}}` and I even tried replacing the Cookie auth type to Bearer and nothing worked.

**Comment by FallenHero66** [comment]
> where you can set the authorization header to `Cookie <cookie_key>` directly into the headers field without scripting

I'm not sure if I understood your request correctly, but I assume you'd like the following header in your request:
```Authorization: Cookie <cookie_key>```

If that's correct, here's how to achieve this:

1. Choose Auth "No Auth"
2. Add Header with name "Authorization" and value "Cookie {{cookie}}"
3. save your cookie value into the environment variable named "cookie"

To my knowledge, what's not possible without scripting at the moment is feeding a cookie value directly into a variable, though.

**Comment by so-jelly** [comment]
i need to add cookies for a top level domain.  it seems this is not happening.   

1. login.example.com -> get cookie for example.com
2. site.example.com -> does not apply example.com cookies

**Comment by mrlectus** [comment]
It doesnt work

**Comment by aggregate1166877** [comment]
Just want to clarify for newcomers - Latest version (v1.38.1) **does in fact store cookies** when you hit a login URL, and does resend those cookies when sending requests to other URLs under the same domain.

This issue seems to be around better cookie management in general (such as easy deletion and editing). I almost didn't use Bruno because I thought it had no cookie support whatsoever, which is no longer the case.

**Comment by nu111** [comment]
Maybe I am wrong, but I think that session cookie is still not stored, possible?

**Comment by aggregate1166877** [comment]
> Maybe I am wrong, but I think that session cookie is still not stored, possible?

It works for me. When I send a POST to my login route, subsequent requests are authenticated. Prior to that, everything is 403.

Are you using the latest version? You should see this in Collection -> Preferences:

![Image](https://github.com/user-attachments/assets/a0cb784e-d5d5-4588-9148-3c689b4a31c9)

**Comment by vsh263** [comment]
> To my knowledge, what's not possible without scripting at the moment is feeding a cookie value directly into a variable, though.
@Infinitay @FallenHero66 
Here's a workaround: https://github.com/usebruno/bruno-docs/issues/71#issuecomment-2818210329

**Comment by anusree-bruno** [comment]
This PR allows access to cookies within scripts: https://github.com/usebruno/bruno/pull/4539

**Comment by VijinV** [comment]
# For anyone else needing to capture cookies from responses and use them in other requests, here's a working test script for all cookies requests:

## ✅ Test Script for Login Request

This script captures cookies from the login response and saves them to an environment variable:

```javascript
// Test script for login request
const cookieHeader = res.headers['set-cookie'];
if (cookieHeader) {
  const cookieString = Array.isArray(cookieHeader)
    ? cookieHeader.join('; ')
    : cookieHeader;
  bru.setEnvVar('fullCookieString', cookieString);
  console.log('Full cookie string saved to environment variables');
}
```
 Pre-request Script for Subsequent Requests
This script retrieves the stored cookies and attaches them to the request headers for authentication:

```javascript
// Pre-request script for other requests
const fullCookieString = bru.getEnvVar('fullCookieString');
if (fullCookieString) {
  req.headers['Cookie'] = fullCookieString;
  console.log('Cookie applied to request');
}
```

**Comment by pooja-bruno** [comment]
This feature is now available in the latest build. Closing the issue. PR: #5117. thanks!
